### ISSUE TITLE
Would you like to develop together?

### ISSUE THREAD

**Issue by SanftMonster** [xbotter/semantic-kernel-LLamaSharp#4]
Hi, this repo is a great work so far!

In fact recently we planed to make such an integration, as you can see in https://github.com/SciSharp/LLamaSharp/issues/9 and https://github.com/microsoft/semantic-kernel/issues/1215. Your work provided a great template for us.

Your experience on ASP.NET core and semantic-kernel is exactly what we need. As an open-source community, we are always open for developers and eager for community efforts joining us. Therefore I sincerely invite you to develop LLamaSharp and the integration with sk with us, to make it a better library for using LLM in local environment. I'll appreciate it if you'd like to join us.

Sincerely,
Rinne

**Comment by xbotter** [comment]
Thank you for reaching out and for your kind words about the repository. I'm glad to hear that.

 I would be honored to join you in developing LLamaSharp and working on the integration with Semantic Kernel. Count me in!

Please let me know how I can get started and contribute. I'm looking forward to collaborating with you and the rest of the community.

**Comment by SanftMonster** [comment]
Hey, I'm very happy that you'd like to come along with us! Please contact me with discord (my id: 1027830405811933204) or email: `AsakusaRinne@gmail.com`. Besides, since I noticed that your location is Shanghai, we can also communicate via QQ (928053669) if you could speak Chinese. :)

**Comment by bc4250** [comment]
it's cool，what about the purpose and roadmap?
The semantic kernel uses api to integrate with OpenAI or compatible API style interface,   do we need to integrate LLM into the same package?  
If we want to  deploy an offline deployment it's a solution.  But the model is continuously evolving and with a large size, and the device's capability is limited,  
There is another  option, build our own GPT capability in .net, without dependency to python or c++.

**Comment by bc4250** [comment]
i have tried this on my PC, it worked! interesting, thank you all!

**Comment by xbotter** [comment]
> it's cool，what about the purpose and roadmap? The semantic kernel uses api to integrate with OpenAI or compatible API style interface, do we need to integrate LLM into the same package? If we want to deploy an offline deployment it's a solution. But the model is continuously evolving and with a large size, and the device's capability is limited, There is another option, build our own GPT capability in .net, without dependency to python or c++.

Currently, the goal is to better integrate LLama into Semantic Kernel. As for the future, we may need to pay attention to the development of LLamSharp.
